import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    root: {
        flex: 1,
        width: "100%",
        backgroundColor: "#ECFAE5",
    },
    dashboardRoot: {
        flex: 1,
        flexDirection: "row",
        backgroundColor: "#ECFAE5",
    },
    dashboardSidebar: {
        width: width > 1024 ? 360 : 300,
        backgroundColor: "#B0DB9C",
        paddingTop: 16,
        paddingHorizontal: 16,
        paddingBottom: 24,
        justifyContent: "space-between",
    },
    dashboardSidebarHeader: {
        marginBottom: 24,
        paddingTop: 8,
    },
    dashboardSidebarTitle: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#1a3d0a",
        marginBottom: 4,
    },
    dashboardSidebarSubtitle: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#365314",
    },
    dashboardNavSection: {
        flex: 1,
        marginTop: 8,
    },
    dashboardNavItem: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginBottom: 4,
    },
    dashboardNavItemActive: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginBottom: 4,
        backgroundColor: "#CAE8BD",
    },
    dashboardNavIcon: {
        marginRight: 12,
    },
    dashboardNavItemText: {
        fontSize: 16,
        color: "#1a3d0a",
        fontFamily: "Poppins_500Medium",
    },
    dashboardNavItemActiveText: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    dashboardSidebarFooter: {
        marginTop: "auto",
        paddingTop: 24,
    },
    dashboardUserProfile: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
    },
    dashboardUserAvatar: {
        width: 40,
        height: 40,
        borderRadius: 16,
        backgroundColor: "#CAE8BD",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    dashboardUserAvatarText: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#1a3d0a",
    },
    dashboardUserInfo: {
        flex: 1,
    },
    dashboardUserName: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
        marginBottom: 2,
    },
    dashboardUserRole: {
        fontSize: 12,
        fontFamily: "Poppins_400Regular",
        color: "#365314",
    },
    dashboardLogoutButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#dc2626",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        width: "100%",
    },
    dashboardLogoutIcon: {
        marginRight: 8,
    },
    dashboardLogoutText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#ffffff",
    },

    dashboardMain: {
        flex: 1,
        backgroundColor: "#ffffff",
        padding: 24,
    },
    dashboardTopBar: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 24,
    },
    dashboardTopTitle: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
    },
    dashboardTopSubtitle: {
        fontSize: 14,
        color: "#64748b",
    },
    dashboardTopRight: {
        alignItems: "flex-end",
    },
    dashboardStatusPill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#DDF6D2",
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 999,
        marginBottom: 8,
    },
    dashboardStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#16a34a",
        marginRight: 4,
    },
    dashboardStatusText: {
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
        color: "#166534",
    },
    dashboardTopDate: {
        fontSize: 12,
        color: "#64748b",
    },
    dashboardScroll: {
        flex: 1,
    },
    dashboardScrollContent: {
        paddingBottom: 32,
        backgroundColor: "#ffffff",
    },
    dashboardStatsRow: {
        flexDirection: width > 1024 ? "row" : "column",
        justifyContent: "space-between",
        marginBottom: 24,
    },
    dashboardStatCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 24,
        marginRight: width > 1024 ? 12 : 0,
        marginBottom: width > 1024 ? 0 : 12,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        elevation: 4,
    },
    dashboardStatIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: "#DDF6D2",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 12,
    },
    dashboardStatIconWrapperWarning: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#ffedd5",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 12,
    },
    dashboardStatIcon: {
        fontSize: 18,
    },
    dashboardStatContent: { alignItems: "center" },
    dashboardStatLabel: {
        fontSize: 13,
        color: "#64748b",
        fontFamily: "Poppins_500Medium",
        textAlign: "center",
    },
    dashboardStatValue: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
    },
    dashboardStatDeltaPositive: {
        fontSize: 12,
        color: "#15803d",
    },
    dashboardStatDeltaNegative: {
        fontSize: 12,
        color: "#b91c1c",
    },
    dashboardTwoColumn: {
        flexDirection: width > 1024 ? "row" : "column",
        justifyContent: "space-between",
    },
    dashboardPanel: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        marginRight: width > 1024 ? 12 : 0,
        marginBottom: width > 1024 ? 0 : 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        elevation: 4,
    },
    dashboardPanelTitle: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 12,
    },
    dashboardAlertItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    dashboardAlertTitle: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 2,
    },
    dashboardAlertSubtitle: {
        fontSize: 13,
        color: "#64748b",
        marginBottom: 2,
    },
    dashboardAlertMeta: {
        fontSize: 12,
        color: "#94a3b8",
    },
    dashboardAlertBadgeCritical: {
        backgroundColor: "#fee2e2",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 999,
    },
    dashboardAlertBadgeWarning: {
        backgroundColor: "#fef3c7",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 999,
    },
    dashboardAlertBadgeAdvisory: {
        backgroundColor: "#e0f2fe",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 999,
    },
    dashboardAlertBadgeText: {
        fontSize: 11,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
    },
    dashboardSensorItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    dashboardSensorTitle: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 2,
    },
    dashboardSensorMeta: {
        fontSize: 12,
        color: "#64748b",
    },
    dashboardSensorMetaStrong: {
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
    },
    dashboardSensorStatusPill: {
        backgroundColor: "#DDF6D2",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 999,
    },
    dashboardSensorStatusText: {
        fontSize: 11,
        fontFamily: "Poppins_700Bold",
        color: "#166534",
    },
    sensorMapContainer: {
        flexDirection: width > 1024 ? "row" : "column",
        flex: 1,
        gap: 16,
    },
    mapPanel: {
        flex: 2,
        minHeight: width > 1024 ? 600 : 400,
    },
    mapView: {
        flex: 1,
        width: "100%",
        height: "100%",
        borderRadius: 16,
        overflow: "hidden",
        position: "relative",
    },
    googleMapContainer: {
        width: "100%",
        height: "100%",
        borderRadius: 16,
        overflow: "hidden",
        position: "relative",
        zIndex: 0,
    },
    webMapContainer: {
        width: "100%",
        height: "100%",
        borderRadius: 16,
        overflow: "hidden",
        position: "relative",
    },
    webMapIframeContainer: {
        width: "100%",
        height: "100%",
        borderRadius: 16,
        overflow: "hidden",
    },
    webMapMarkersOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: "box-none",
    },
    webMapMarker: {
        position: "absolute",
        transform: [{ translateX: -18 }, { translateY: -18 }],
        pointerEvents: "auto",
        zIndex: 10,
    },
    webMapMarkerSelected: {
        transform: [{ translateX: -22 }, { translateY: -22 }, { scale: 1.2 }],
        zIndex: 20,
    },
    mapPlaceholder: {
        flex: 1,
        backgroundColor: "#ECFAE5",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        overflow: "hidden",
    },
    mapPlaceholderTitle: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 8,
    },
    mapPlaceholderSubtitle: {
        fontSize: 14,
        color: "#64748b",
        textAlign: "center",
        marginBottom: 4,
    },
    mapMarkersContainer: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: "100%",
        height: "100%",
    },
    sensorMarker: {
        position: "absolute",
        width: 40,
        height: 40,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
        borderWidth: 3,
        borderColor: "#ffffff",
    },
    sensorMarkerSelected: {
        width: 50,
        height: 50,
        borderRadius: 25,
        borderWidth: 4,
        borderColor: "#B0DB9C",
        shadowColor: "#B0DB9C",
        shadowOpacity: 0.5,
        shadowRadius: 12,
    },
    mapMarkerContainer: {
        alignItems: "center",
        justifyContent: "center",
    },
    mapMarkerPin: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 3,
        borderColor: "#ffffff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    mapMarkerSelected: {
        transform: [{ scale: 1.2 }],
    },
    sensorInfoOverlay: {
        position: "absolute",
        top: 20,
        right: 20,
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        minWidth: 200,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: "#DDF6D2",
    },
    sensorInfoTitle: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
    },
    sensorInfoText: {
        fontSize: 14,
        color: "#64748b",
        marginBottom: 8,
    },
    sensorInfoStatusRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    sensorInfoStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 4,
    },
    sensorInfoStatusText: {
        fontSize: 13,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
    },
    sensorInfoTime: {
        fontSize: 12,
        color: "#94a3b8",
        marginBottom: 8,
    },
    sensorInfoClose: {
        position: "absolute",
        top: 12,
        right: 12,
        padding: 8,
        zIndex: 100,
        backgroundColor: "rgba(241, 245, 249, 0.8)",
        borderRadius: 16,
    },
    sensorListPanel: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        padding: 16,
        minWidth: width > 1024 ? 300 : "100%",
    },
    sensorListTitle: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 16,
    },
    sensorListScroll: {
        flex: 1,
    },
    sensorListContent: {
        paddingBottom: 8,
    },
    sensorListItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 8,
        marginBottom: 8,
        backgroundColor: "#f8fafc",
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    sensorListItemSelected: {
        backgroundColor: "#ECFAE5",
        borderColor: "#CAE8BD",
        borderWidth: 2,
    },
    sensorListItemContent: {
        flex: 1,
    },
    sensorListItemName: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 2,
    },
    sensorListItemBarangay: {
        fontSize: 12,
        color: "#64748b",
    },
    sensorListItemDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginLeft: 12,
    },
    container: {
        flex: 1,
        backgroundColor: "#ECFAE5",
        width: "100%",
    },
    scrollView: {
        flex: 1,
        width: "100%",
        backgroundColor: "transparent",
    },
    scrollContent: {
        flexGrow: 1,
        width: "100%",
        paddingBottom: 16,
    },
    nav: {
        backgroundColor: "rgba(255, 255, 255, 0.98)",
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
        width: "100%",
        paddingVertical: 16,
        paddingHorizontal: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    navSticky: {
        position: "sticky",
        top: 0,
        zIndex: 20,
    },
    navInner: {
        width: "100%",
        maxWidth: 1200,
        alignSelf: "center",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    brand: {
        flexDirection: "row",
        alignItems: "center",
    },
    logoMark: {
        width: 64,
        height: 64,
        borderRadius: 12,
        backgroundColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    logoImage: {
        width: 64,
        height: 64,
    },
    brandText: {
        marginLeft: 12,
    },
    brandTitle: {
        fontSize: 22,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        letterSpacing: -0.3,
    },
    brandSubtitle: {
        fontSize: 12,
        color: "#64748b",
    },
    navLinks: {
        flexDirection: "row",
        alignItems: "center",
    },
    navLinkBtn: {
        marginRight: 24,
    },
    navLink: {
        fontSize: 15,
        color: "#475569",
        fontFamily: "Poppins_500Medium",
    },
    navCta: {
        backgroundColor: "#B0DB9C",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 16,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    navCtaText: {
        color: "#1a3d0a",
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
    },
    hero: {
        width: "100%",
        paddingVertical: 100,
        paddingHorizontal: 24,
        position: "relative",
    },
    heroContent: {
        width: "100%",
        maxWidth: 1200,
        alignSelf: "center",
    },
    heroGrid: {
        flexDirection: width > 1024 ? "row" : "column",
        alignItems: "center",
        justifyContent: "space-between",
    },
    heroCopy: {
        flex: 1,
        marginRight: width > 1024 ? 48 : 0,
        marginBottom: width > 1024 ? 0 : 40,
    },
    heroBadge: {
        backgroundColor: "#DDF6D2",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 25,
        alignSelf: "flex-start",
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "#CAE8BD",
    },
    heroBadgeText: {
        color: "#2d5016",
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        letterSpacing: 0.5,
    },
    heroTitle: {
        fontSize: width > 768 ? 56 : 40,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 24,
        lineHeight: width > 768 ? 64 : 48,
        letterSpacing: -0.5,
    },
    heroSubtitle: {
        fontSize: 20,
        color: "#64748b",
        marginBottom: 32,
        lineHeight: 32,
        maxWidth: 600,
    },
    heroActions: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    primaryBtn: {
        backgroundColor: "#B0DB9C",
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        marginRight: 16,
        marginBottom: 12,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 6,
    },
    primaryBtnText: {
        color: "#1a3d0a",
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        letterSpacing: 0.5,
    },
    ghostBtn: {
        backgroundColor: "transparent",
        borderWidth: 2,
        borderColor: "#cbd5e1",
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        marginBottom: 12,
    },
    ghostBtnText: {
        color: "#475569",
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
    },
    heroPreview: {
        flex: 1,
        maxWidth: 400,
        width: "100%",
    },
    previewCard: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 8,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    previewHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    previewHeaderText: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#64748b",
    },
    statusPill: {
        backgroundColor: "#DDF6D2",
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 12,
    },
    statusPillText: {
        color: "#1a3d0a",
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
    },
    previewRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    previewRowLabel: {
        fontSize: 14,
        color: "#64748b",
    },
    previewRowValue: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
    },
    section: {
        width: "100%",
        paddingVertical: 100,
        paddingHorizontal: 24,
        backgroundColor: "#ffffff",
    },
    sectionContent: {
        width: "100%",
        maxWidth: 1200,
        alignSelf: "center",
    },
    sectionHeader: {
        alignItems: "center",
        marginBottom: 48,
    },
    sectionTitleLarge: {
        fontSize: width > 768 ? 42 : 32,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        textAlign: "center",
        marginBottom: 16,
        letterSpacing: -0.5,
    },
    sectionSubtitle: {
        fontSize: 18,
        color: "#64748b",
        textAlign: "center",
        maxWidth: 600,
        lineHeight: 28,
    },
    splitCard: {
        flexDirection: width > 1024 ? "row" : "column",
        backgroundColor: "#ffffff",
        borderRadius: 28,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 24,
        elevation: 8,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    imagePanel: {
        flex: 1,
        height: width > 1024 ? 400 : 300,
        position: "relative",
    },
    image: {
        width: "100%",
        height: "100%",
    },
    imageOverlay: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        padding: 24,
    },
    imageCaption: {
        marginTop: "auto",
    },
    imageCaptionBadge: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#ffffff",
        marginBottom: 12,
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    imageCaptionTitle: {
        fontSize: 28,
        fontFamily: "Poppins_700Bold",
        color: "#ffffff",
        lineHeight: 34,
    },
    textPanel: {
        flex: 1,
        padding: 32,
        justifyContent: "center",
    },
    sectionBadge: {
        backgroundColor: "#fee2e2",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 25,
        alignSelf: "flex-start",
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#fecaca",
    },
    sectionBadgeText: {
        color: "#991b1b",
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        letterSpacing: 0.5,
    },
    sectionBadgeWhite: {
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 25,
        alignSelf: "center",
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.5)",
    },
    sectionBadgeTextWhite: {
        color: "#1a3d0a",
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        letterSpacing: 0.5,
    },
    sectionTitle: {
        fontSize: width > 768 ? 36 : 28,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 16,
        letterSpacing: -0.4,
    },
    textPanelDescription: {
        fontSize: 17,
        color: "#64748b",
        lineHeight: 28,
        marginBottom: 24,
    },
    infoList: {
        marginTop: 8,
    },
    infoListItem: {
        flexDirection: "row",
        alignItems: "flex-start",
        marginBottom: 16,
    },
    icon: {
        width: 40,
        height: 40,
        borderRadius: 16,
        backgroundColor: "#DDF6D2",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 16,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    iconText: {
        fontSize: 18,
    },
    infoListContent: {
        flex: 1,
    },
    infoListTitle: {
        fontSize: 17,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
    },
    infoListText: {
        fontSize: 14,
        color: "#64748b",
        lineHeight: 20,
    },
    checkIcon: {
        fontSize: 20,
        color: "#B0DB9C",
        marginRight: 12,
        marginTop: 2,
    },
    featuresGrid: {
        flexDirection: width > 768 ? "row" : "column",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    featureCard: {
        width: width > 768 ? "23%" : "100%",
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 24,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "#f1f5f9",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    featureIcon: {
        width: 64,
        height: 64,
        borderRadius: 16,
        backgroundColor: "#DDF6D2",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 4,
    },
    featureIconText: {
        fontSize: 24,
    },
    featureTitle: {
        fontSize: 22,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 12,
        letterSpacing: -0.3,
    },
    featureDescription: {
        fontSize: 15,
        color: "#64748b",
        lineHeight: 24,
    },
    preventionSection: {
        width: "100%",
        paddingVertical: 80,
        paddingHorizontal: 24,
        backgroundColor: "#B0DB9C",
    },
    preventionTitle: {
        fontSize: width > 768 ? 48 : 36,
        fontFamily: "Poppins_700Bold",
        color: "#1a3d0a",
        textAlign: "center",
        marginBottom: 16,
        letterSpacing: -0.5,
    },
    preventionSubtitle: {
        fontSize: 20,
        color: "#2d5016",
        textAlign: "center",
        maxWidth: 700,
        alignSelf: "center",
        lineHeight: 30,
    },
    preventionGrid: {
        flexDirection: width > 1024 ? "row" : "column",
        justifyContent: "space-between",
        marginTop: 48,
    },
    preventionCard: {
        width: width > 1024 ? "31%" : "100%",
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 24,
        marginBottom: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 6,
    },
    preventionIcon: {
        width: 56,
        height: 56,
        borderRadius: 16,
        backgroundColor: "#DDF6D2",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    preventionIconText: {
        fontSize: 24,
    },
    preventionCardTitle: {
        fontSize: 22,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 16,
        letterSpacing: -0.3,
    },
    preventionList: {
        marginTop: 8,
    },
    preventionListItem: {
        fontSize: 15,
        color: "#475569",
        marginBottom: 12,
        lineHeight: 24,
    },
    statsSection: {
        width: "100%",
        paddingVertical: 80,
        paddingHorizontal: 24,
        backgroundColor: "#CAE8BD",
        position: "relative",
    },
    statsGrid: {
        flexDirection: width > 768 ? "row" : "column",
        justifyContent: "space-around",
        alignItems: "center",
    },
    statItem: {
        alignItems: "center",
        marginBottom: width > 768 ? 0 : 32,
    },
    statNumber: {
        fontSize: width > 768 ? 56 : 42,
        fontFamily: "Poppins_700Bold",
        color: "#1a3d0a",
        marginBottom: 12,
        letterSpacing: -1,
    },
    statLabel: {
        fontSize: 16,
        color: "#2d5016",
        fontFamily: "Poppins_500Medium",
        letterSpacing: 0.5,
    },
    adminGrid: {
        flexDirection: width > 1024 ? "row" : "column",
        alignItems: "center",
        justifyContent: "space-between",
    },
    adminCopy: {
        flex: 1,
        marginRight: width > 1024 ? 48 : 0,
        marginBottom: width > 1024 ? 0 : 40,
    },
    adminPreview: {
        flex: 1,
        maxWidth: 400,
        width: "100%",
    },
    footer: {
        width: "100%",
        paddingVertical: 80,
        paddingHorizontal: 24,
        backgroundColor: "#7a9c6a",
    },
    footerGrid: {
        flexDirection: width > 768 ? "row" : "column",
        justifyContent: "space-between",
        marginBottom: 32,
    },
    footerColumn: {
        width: width > 768 ? "23%" : "100%",
        marginBottom: width > 768 ? 0 : 32,
    },
    footerBrandTitle: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
        color: "#ECFAE5",
        marginLeft: 12,
    },
    footerTitle: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#ffffff",
        marginBottom: 16,
        letterSpacing: 0.3,
    },
    footerText: {
        fontSize: 14,
        color: "#94a3b8",
        lineHeight: 20,
        marginTop: 12,
    },
    footerLink: {
        fontSize: 14,
        color: "#94a3b8",
        marginBottom: 12,
        lineHeight: 24,
    },
    footerBottom: {
        width: "100%",
        alignItems: "center",
        paddingTop: 32,
        borderTopWidth: 1,
        borderTopColor: "rgba(255, 255, 255, 0.2)",
    },
    footerBottomText: {
        fontSize: 12,
        color: "#DDF6D2",
    },
    modalOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
    },
    modal: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        width: "90%",
        maxWidth: 440,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.4,
        shadowRadius: 24,
        elevation: 12,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 24,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
    },
    modalTitle: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#1e293b",
    },
    modalClose: {
        width: 32,
        height: 32,
        alignItems: "center",
        justifyContent: "center",
    },
    modalCloseText: {
        fontSize: 24,
        color: "#64748b",
    },
    modalBody: {
        padding: 24,
    },
    accessLevelContainer: {
        marginBottom: 24,
    },
    accessLevelLabel: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#475569",
        marginBottom: 12,
    },
    accessLevelButtons: {
        flexDirection: "row",
    },
    accessLevelButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#ffffff",
        alignItems: "center",
        marginRight: 8,
    },
    accessLevelButtonActive: {
        backgroundColor: "#DDF6D2",
        borderColor: "#B0DB9C",
    },
    accessLevelButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#64748b",
    },
    accessLevelButtonTextActive: {
        color: "#1a3d0a",
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#475569",
        marginBottom: 8,
    },
    modalInput: {
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        paddingVertical: 12,
        paddingHorizontal: 16,
        fontSize: 16,
        color: "#1e293b",
        backgroundColor: "#ffffff",
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        paddingHorizontal: 12,
        backgroundColor: "#ffffff",
    },
    inputIcon: {
        fontSize: 18,
        marginRight: 8,
    },
    input: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 16,
        color: "#1e293b",
        outlineStyle: "none",
    },
    rememberForgotRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 24,
    },
    rememberMeContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    rememberMeText: {
        fontSize: 14,
        color: "#1e293b",
        marginLeft: 8,
    },
    forgotPasswordText: {
        fontSize: 14,
        color: "#B0DB9C",
        fontFamily: "Poppins_500Medium",
    },
    errorBox: {
        backgroundColor: "#fee2e2",
        borderWidth: 1,
        borderColor: "#fecaca",
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
    },
    errorText: {
        color: "#991b1b",
        fontSize: 14,
    },
    modalButton: {
        borderRadius: 12,
        overflow: "hidden",
        marginTop: 8,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 6,
    },
    modalButtonGradient: {
        paddingVertical: 16,
        alignItems: "center",
        justifyContent: "center",
    },
    modalButtonText: {
        color: "#1a3d0a",
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        letterSpacing: 0.5,
    },
    demoBox: {
        backgroundColor: "#f8fafc",
        borderRadius: 8,
        padding: 16,
        marginTop: 24,
    },
    demoTitle: {
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
        color: "#475569",
        marginBottom: 8,
    },
    demoText: {
        fontSize: 13,
        color: "#475569",
        marginBottom: 4,
        lineHeight: 20,
    },
    // Alert Management Page Styles
    alertManagementContainer: {
        flexDirection: width > 1024 ? "row" : "column",
        flex: 1,
        gap: 16,
        paddingHorizontal: 24,
        paddingBottom: 24,
    },
    alertBroadcastPanelContainer: {
        flex: 1,
        position: 'relative',
    },
    alertBroadcastPanel: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    alertPanelBack: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    alertVerificationsPanelContainer: {
        flex: 1,
        position: 'relative',
    },
    alertVerificationsPanel: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    alertPanelHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 24,
    },
    alertPanelTitle: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        letterSpacing: -0.3,
    },
    flipToggleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 16,
        backgroundColor: '#BDD8E9',
        borderWidth: 1.5,
        borderColor: '#7BBDE8',
        transition: 'all 0.2s ease',
    },
    flipToggleButtonHover: {
        backgroundColor: '#7BBDE8',
        borderColor: '#49769F',
        transform: [{ scale: 1.02 }],
    },
    flipToggleButtonText: {
        fontSize: 13,
        fontFamily: "Poppins_700Bold",
        color: '#0A4174',
    },
    flipToggleButtonTextHover: {
        color: '#001D39',
    },
    alertInputGroup: {
        marginBottom: 24,
    },
    alertInputLabel: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#475569",
        marginBottom: 12,
    },
    alertTypeButtons: {
        flexDirection: "row",
        gap: 12,
    },
    alertTypeButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#ffffff",
        alignItems: "center",
        justifyContent: "center",
    },
    alertTypeButtonActive: {
        borderWidth: 2,
    },
    alertTypeButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#64748b",
    },
    barangayCheckboxList: {
        gap: 12,
    },
    barangayCheckboxItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: "#cbd5e1",
        alignItems: "center",
        justifyContent: "center",
    },
    checkboxChecked: {
        borderWidth: 2,
    },
    barangayCheckboxLabel: {
        fontSize: 15,
        color: "#1e293b",
        fontFamily: "Poppins_500Medium",
    },
    alertMessageInput: {
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        padding: 16,
        fontSize: 15,
        color: "#1e293b",
        backgroundColor: "#ffffff",
        minHeight: 120,
        textAlignVertical: "top",
    },
    alertMessageCounter: {
        fontSize: 12,
        color: "#94a3b8",
        marginTop: 8,
        textAlign: "right",
    },
    broadcastButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 16,
        gap: 8,
        marginTop: 8,
    },
    broadcastButtonDisabled: {
        backgroundColor: "#f1f5f9",
        opacity: 0.6,
    },
    broadcastButtonText: {
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    verificationsScroll: {
        flex: 1,
    },
    verificationsScrollContent: {
        gap: 16,
        paddingBottom: 8,
    },
    noVerifications: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 64,
    },
    noVerificationsText: {
        fontSize: 15,
        color: "#94a3b8",
        marginTop: 16,
        fontFamily: "Poppins_500Medium",
    },
    verificationCard: {
        backgroundColor: "#f8fafc",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    verificationHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    verificationSourceBadge: {
        backgroundColor: "#ECFAE5",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
    },
    verificationSourceText: {
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    verificationTimestamp: {
        fontSize: 12,
        color: "#94a3b8",
        fontFamily: "Poppins_500Medium",
    },
    verificationBarangay: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 8,
    },
    // Reports Preview on Front Side
    reportsPreviewList: {
        backgroundColor: '#f8fafc',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        gap: 8,
    },
    reportPreviewItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    reportPreviewDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#166534',
    },
    reportPreviewText: {
        fontSize: 13,
        fontFamily: "Poppins_600SemiBold",
        color: '#1e293b',
    },
    reportPreviewLocation: {
        fontSize: 11,
        color: '#64748b',
        fontFamily: "Poppins_500Medium",
    },
    verificationMessage: {
        fontSize: 15,
        color: "#1e293b",
        marginBottom: 8,
        lineHeight: 22,
    },
    verificationReporter: {
        fontSize: 13,
        color: "#64748b",
        marginBottom: 16,
    },
    verificationActions: {
        flexDirection: "row",
        gap: 12,
    },
    verifyButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        gap: 4,
    },
    verifyButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    rejectButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        gap: 4,
    },
    rejectButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
    },
    // System Health Page Styles
    healthSummaryRow: {
        flexDirection: width > 1024 ? "row" : "column",
        gap: 16,
        marginBottom: 24,
    },
    healthSummaryCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        position: "relative",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    healthSummaryCardStatus: {
        position: "absolute",
        top: 12,
        right: 12,
    },
    healthSummaryStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#16a34a",
    },
    healthSummaryCardIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: "#ECFAE5",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    healthSummaryValue: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
        letterSpacing: -0.5,
    },
    healthSummaryLabel: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#64748b",
    },
    healthTableSection: {
        marginBottom: 24,
    },
    healthTableTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 16,
        letterSpacing: -0.3,
    },
    healthTableCard: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    healthTableHeader: {
        flexDirection: "row",
        backgroundColor: "#f8fafc",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
        alignItems: "center",
    },
    healthTableHeaderCell: {
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
        color: "#475569",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    healthTableColId: {
        flex: 1.2,
    },
    healthTableColLocation: {
        flex: 1.8,
    },
    healthTableColStatus: {
        flex: 1.2,
    },
    healthTableColMetric: {
        flex: 1,
    },
    healthTableColUpdate: {
        flex: 1.2,
    },
    healthTableRow: {
        flexDirection: "row",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
        alignItems: "center",
    },
    healthTableRowOffline: {
        backgroundColor: "#fef2f2",
    },
    healthTableCell: {
        flexDirection: "row",
        alignItems: "center",
    },
    healthTableCellText: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#1e293b",
    },
    healthTableCellTextMuted: {
        fontSize: 13,
        color: "#64748b",
        fontFamily: "Poppins_500Medium",
    },
    healthStatusBadge: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        borderWidth: 1,
        alignSelf: "flex-start",
    },
    healthStatusBadgeText: {
        fontSize: 11,
        fontFamily: "Poppins_700Bold",
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },
    // Data & Reports Page Styles
    reportsContainer: {
        paddingHorizontal: 24,
        paddingBottom: 24,
    },
    reportsTopRow: {
        flexDirection: width > 1024 ? "row" : "column",
        gap: 16,
        marginBottom: 24,
    },
    reportGenerateCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    dataOverviewCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    reportCardHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
        gap: 12,
    },
    reportCardTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        letterSpacing: -0.3,
    },
    reportFieldGroup: {
        marginBottom: 16,
    },
    reportFieldLabel: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#475569",
        marginBottom: 8,
    },
    reportTypeOptions: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    reportTypeOption: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#ffffff",
    },
    reportTypeOptionActive: {
        backgroundColor: "#ECFAE5",
        borderColor: "#B0DB9C",
    },
    reportTypeOptionText: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#64748b",
    },
    reportTypeOptionTextActive: {
        color: "#1a3d0a",
        fontFamily: "Poppins_600SemiBold",
    },
    reportDateRow: {
        flexDirection: width > 768 ? "row" : "column",
        gap: 16,
    },
    reportInputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        paddingHorizontal: 12,
        backgroundColor: "#ffffff",
    },
    reportDateInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 15,
        color: "#1e293b",
        outlineStyle: "none",
    },
    exportFormatRow: {
        flexDirection: "row",
        gap: 12,
    },
    exportFormatButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#ffffff",
        alignItems: "center",
        justifyContent: "center",
    },
    exportFormatButtonActive: {
        backgroundColor: "#1a3d0a",
        borderColor: "#1a3d0a",
    },
    exportFormatButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#64748b",
    },
    exportFormatButtonTextActive: {
        color: "#ffffff",
    },
    generateReportButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 16,
        backgroundColor: "#B0DB9C",
        gap: 8,
        marginTop: 8,
    },
    generateReportButtonDisabled: {
        backgroundColor: "#f1f5f9",
        opacity: 0.7,
    },
    generateReportButtonText: {
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    generateReportButtonTextDisabled: {
        color: "#94a3b8",
    },
    dataOverviewList: {
        gap: 12,
    },
    dataOverviewRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
    },
    dataOverviewLabel: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#475569",
    },
    dataOverviewValue: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
    },
    recentReportsCard: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    recentReportsList: {
        gap: 12,
    },
    recentReportItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 16,
        paddingHorizontal: 16,
        backgroundColor: "#f8fafc",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    recentReportInfo: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    recentReportName: {
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 4,
    },
    recentReportMeta: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    recentReportMetaText: {
        fontSize: 13,
        color: "#64748b",
    },
    downloadReportButton: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: "#ECFAE5",
        borderWidth: 1,
        borderColor: "#B0DB9C",
        gap: 4,
    },
    downloadReportButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    // User Management Page Styles
    userStatsRow: {
        flexDirection: width > 1024 ? "row" : "column",
        gap: 16,
        marginBottom: 24,
    },
    userStatsCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        flexDirection: "column",
        justifyContent: "space-between",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    userStatsIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: "#eff6ff",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    userStatsValue: {
        fontSize: 28,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
        letterSpacing: -0.5,
    },
    userStatsLabel: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#64748b",
    },
    filterBar: {
        flexDirection: width > 1024 ? "row" : "column",
        justifyContent: "space-between",
        alignItems: width > 1024 ? "center" : "stretch",
        marginBottom: 24,
        gap: 16,
        zIndex: 100,
        position: 'relative',
    },
    searchContainer: {
        flex: 1,
        maxWidth: width > 1024 ? 400 : "100%",
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#ffffff",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        paddingHorizontal: 12,
    },
    searchInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 15,
        color: "#1e293b",
        outlineStyle: "none",
    },
    filterGroup: {
        flexDirection: "row",
        gap: 12,
    },
    filterSelect: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#ffffff",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        paddingVertical: 8,
        paddingHorizontal: 16,
        gap: 8,
    },
    filterSelectText: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#475569",
    },
    ccFilterDropdown: {
        position: 'absolute',
        top: '120%',
        left: 0,
        minWidth: 160,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        padding: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
        zIndex: 5000,
    },
    ccFilterItem: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
    ccFilterItemText: {
        fontSize: 14,
        color: '#475569',
        fontFamily: "Poppins_500Medium",
    },
    addUserButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#2563eb",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        gap: 8,
        justifyContent: "center",
        shadowColor: "#2563eb",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    addUserButtonText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#ffffff",
    },
    userTableContainer: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#DDF6D2",
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    userTableHeader: {
        flexDirection: "row",
        backgroundColor: "#f8fafc",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
        alignItems: "center",
    },
    userTableHeaderCell: {
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
        color: "#475569",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    userColUser: { flex: 2 },
    userColRole: { flex: 1 },
    userColLocation: { flex: 1.5 },
    userColStatus: { flex: 1 },
    userColJoined: { flex: 1 },
    userColActions: { flex: 0.8, alignItems: "flex-end" },
    userTableRow: {
        flexDirection: "row",
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
        alignItems: "center",
        backgroundColor: "#ffffff",
    },
    userCellUser: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    userAvatar: {
        width: 40,
        height: 40,
        borderRadius: 16,
        backgroundColor: "#eff6ff",
        alignItems: "center",
        justifyContent: "center",
    },
    userAvatarText: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#2563eb",
    },
    userName: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#0f172a",
        marginBottom: 2,
    },
    userEmail: {
        fontSize: 13,
        color: "#64748b",
    },
    userRoleBadge: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        alignSelf: "flex-start",
    },
    userRoleBadgeText: {
        fontSize: 11,
        fontFamily: "Poppins_700Bold",
        // color: "#ffffff",
    },
    userStatusBadge: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        alignSelf: "flex-start",
        gap: 4,
    },
    userStatusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    userStatusText: {
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
    },
    userCellText: {
        fontSize: 14,
        color: "#1e293b",
    },
    userActionButtons: {
        flexDirection: "row",
        gap: 8,
    },
    userActionButton: {
        width: 32,
        height: 32,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#f8fafc",
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },

    // Threshold Config Page Styles
    configGrid: {
        flexDirection: width > 1024 ? "row" : "column",
        gap: 24,
        marginBottom: 24,
    },
    configLeftCol: {
        flex: 1.2,
        gap: 24,
    },
    configRightCol: {
        flex: 0.8,
        gap: 24,
    },
    configCard: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 24,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        elevation: 4,
    },
    configCardHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 24,
    },
    configCardTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
    },
    thresholdRow: {
        marginBottom: 16,
    },
    thresholdLabelRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    thresholdLabel: {
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
        color: "#1e293b",
    },
    thresholdBadge: {
        paddingVertical: 2,
        paddingHorizontal: 8,
        borderRadius: 12,
        backgroundColor: "#eff6ff",
    },
    thresholdBadgeText: {
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
        color: "#3b82f6",
    },
    thresholdInputDisplay: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 4,
    },
    thresholdDescription: {
        fontSize: 13,
        color: "#64748b",
        lineHeight: 20,
    },
    visualRefContainer: {
        height: 300,
        position: "relative",
        borderRadius: 12,
        overflow: "hidden",
        marginBottom: 16,
    },
    visualGradient: {
        width: "100%",
        height: "100%",
        // Placeholder for gradient, actual gradient applied via style prop or LinearGradient component
    },
    visualLabelOverlay: {
        position: "absolute",
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: "space-between",
        padding: 16,
    },
    visualLabelItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    visualLabelText: {
        color: "#ffffff",
        fontFamily: "Poppins_700Bold",
        fontSize: 14,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    warningNote: {
        backgroundColor: "#fffbeb",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#fcd34d",
        flexDirection: "row",
        gap: 12,
    },
    warningNoteTitle: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#92400e",
        marginBottom: 4,
    },
    warningNoteText: {
        fontSize: 13,
        color: "#b45309",
        lineHeight: 20,
    },
    saveConfigButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#B0DB9C",
        paddingVertical: 12,
        borderRadius: 16,
        marginTop: 12,
        gap: 8,
        shadowColor: "#B0DB9C",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    saveConfigButtonText: {
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
        color: "#1a3d0a",
    },
    settingInputGroup: {
        flex: 1,
    },
    settingInputLabel: {
        fontSize: 14,
        fontFamily: "Poppins_500Medium",
        color: "#475569",
        marginBottom: 8,
    },
    settingInput: {
        backgroundColor: "#ffffff",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        paddingVertical: 12,
        paddingHorizontal: 16,
        fontSize: 15,
        color: "#0f172a",
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999,
    },
    loadingBox: {
        backgroundColor: 'white',
        padding: 16,
        borderRadius: 16,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    loadingText: {
        marginTop: 8,
        color: '#4a7c59',
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
    },
    // Modal Styles
    modalOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000,
    },
    modal: {
        backgroundColor: "#fff",
        borderRadius: 16,
        width: "90%",
        maxWidth: 400,
        padding: 0,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    modalTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
    },
    modalClose: {
        padding: 4,
    },
    modalCloseText: {
        fontSize: 18,
        color: "#64748b",
    },
    modalBody: {
        padding: 24,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#475569",
        marginBottom: 4,
    },
    modalInput: {
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#0f172a",
        backgroundColor: "#ffffff",
    },
    modalButton: {
        marginTop: 12,
        shadowColor: "#166534",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
        borderRadius: 8,
    },
    modalButtonGradient: {
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        width: "100%",
    },
    modalButtonText: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#ffffff",
    },
    // --- Live Sensor Status Component Styles ---
    liveSensorSection: {
        width: "100%",
        marginBottom: 24,
    },
    liveSensorHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
    },
    liveSensorTitle: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#1a3d0a",
    },
    liveSensorScrollContent: {
        paddingVertical: 8, // padding for shadow
        paddingHorizontal: 4,
        flexGrow: 1,
    },
    liveSensorCard: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 32,
        flex: 1,
        minWidth: 340,
        marginRight: 24,
        alignItems: "center", // Center contents horizontally
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 4,
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.03)",
    },
    sensorCardHeader: {
        alignItems: "center",
        marginBottom: 16,
    },
    sensorCardName: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        marginBottom: 2,
    },
    sensorCardLocation: {
        fontSize: 12,
        fontFamily: "Poppins_400Regular",
        color: "#64748b",
    },
    sensorPillContainer: {
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 32,
        marginTop: 16,
    },
    sensorPillTrack: {
        width: 64,
        height: 180, // Match the height in the image roughly
        backgroundColor: "#f4f4f5", // Light gray track
        borderRadius: 32,
        overflow: "hidden", // Clip internal fill
        justifyContent: "flex-end", // Fill grows from bottom to top
        position: "relative",
    },
    sensorPillFill: {
        width: "100%",
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
    },
    sensorPillMarkers: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: "space-between",
        paddingVertical: 8,
        zIndex: 10,
    },
    sensorPillMarkerLine: {
        width: "100%",
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0,0,0,0.05)", // Faint horizontal lines
        alignItems: "center",
        justifyContent: "flex-end", // Position text at the top of the line
        height: "25%", // Divides the 140px height into 4 sections
        paddingBottom: 2,
    },
    sensorPillMarkerText: {
        fontSize: 10,
        fontFamily: "Poppins_500Medium",
        color: "#64748b",
        marginBottom: 2,
    },
    sensorCardValueSection: {
        alignItems: "center",
        marginBottom: 32,
    },
    sensorCardValueLabel: {
        fontSize: 36,
        fontFamily: "Poppins_700Bold",
        color: "#0f172a",
        lineHeight: 40,
    },
    sensorCardValueUnit: {
        fontSize: 18,
        fontFamily: "Poppins_600SemiBold",
        color: "#64748b",
    },
    sensorCardBadge: {
        paddingVertical: 4,
        paddingHorizontal: 16,
        borderRadius: 16,
        marginTop: 8,
    },
    sensorCardBadgeText: {
        fontSize: 11,
        fontFamily: "Poppins_700Bold",
        letterSpacing: 0.5,
    },
    sensorCardFooter: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: "rgba(0,0,0,0.05)",
    },
    sensorCardFooterStat: {
        flexDirection: "row",
        alignItems: "center",
    },
    sensorCardFooterText: {
        fontSize: 10,
        fontFamily: "Poppins_500Medium",
        color: "#64748b",
    },
    sensorCardFooterTime: {
        fontSize: 10,
        fontFamily: "Poppins_400Regular",
        color: "#94a3b8",
    },
    liveSensorEmpty: {
        padding: 32,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    liveSensorEmptyText: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#64748b",
    },
    // --- COMMAND CENTER 2.0 REDESIGN STYLES ---
    ccHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    ccTabContainer: {
        flexDirection: 'row',
        backgroundColor: '#f1f5f9',
        borderRadius: 12,
        padding: 4,
        alignSelf: 'flex-start',
        marginBottom: 24,
    },
    ccTab: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 16,
        gap: 8,
    },
    ccTabActive: {
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    ccTabText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: '#64748b',
    },
    ccTabTextActive: {
        color: '#0f172a',
    },
    ccAuditBadge: {
        backgroundColor: '#0f172a',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        marginLeft: 4,
    },
    ccAuditBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontFamily: "Poppins_700Bold",
    },

    // Mission Control (Operations Tab)
    ccOpsGrid: {
        flexDirection: 'row',
        gap: 16,
        flex: 1,
        overflow: 'hidden',
    },
    ccOpsLeft: {
        flex: 1.5,
        overflow: 'hidden',
    },
    ccOpsRight: {
        flex: 1,
        overflow: 'hidden',
    },
    ccPanel: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 24,
        borderWidth: 1,
        borderColor: '#f1f5f9',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
        elevation: 2,
        marginBottom: 16,
    },
    ccPanelHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    ccPanelTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: '#0f172a',
    },
    ccPanelSubtitle: {
        fontSize: 13,
        color: '#64748b',
        marginTop: 2,
    },

    // Refined Alert Cards
    ccAlertCard: {
        backgroundColor: '#f8fafc',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    ccAlertCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    ccAlertLevelBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 16,
    },
    ccAlertLevelText: {
        fontSize: 11,
        fontFamily: "Poppins_700Bold",
    },
    ccAlertProgressContainer: {
        height: 4,
        backgroundColor: '#e2e8f0',
        borderRadius: 2,
        marginVertical: 12,
        overflow: 'hidden',
    },
    ccAlertProgressBar: {
        height: '100%',
        borderRadius: 2,
    },
    ccAlertActionRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
        flexWrap: 'wrap',
    },
    ccActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 16,
        gap: 4,
        minHeight: 36,
    },
    ccActionButtonText: {
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
    },

    // Broadcast Studio
    ccBroadcastGrid: {
        flexDirection: 'row',
        gap: 24,
        flex: 1,
        overflow: 'hidden',
    },
    ccFormSection: {
        flex: 1,
        overflow: 'hidden',
    },
    ccHistorySection: {
        width: 380,
        overflow: 'hidden',
    },
    ccBrgyGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 8,
    },
    ccBrgyChip: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 16,
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    ccBrgyChipActive: {
        backgroundColor: '#eff6ff',
        borderColor: '#3b82f6',
    },
    ccBrgyChipText: {
        fontSize: 13,
        color: '#64748b',
        fontFamily: "Poppins_500Medium",
    },
    ccBrgyChipTextActive: {
        color: '#1d4ed8',
        fontFamily: "Poppins_600SemiBold",
    },
});
